### ISSUE TITLE
IDNA support

### ISSUE THREAD

**Issue by shadowfacts** [karwa/swift-url#147]
IDNA domain fragments are currently detected but not parsed; it would be great if they were fully supported.

It looks like what needs to be done is:
1. In `ParsedHost._parseASCIIDomain`, if any component starts with the IDNA prefix, set a flag on the domain info rather than returning an error
2. In `ParsedHost.write`, decode the IDNA components
    1. Split the domain into individual labels
    2. Run the [ToUnicode](https://datatracker.ietf.org/doc/html/rfc3490#section-4.2) operation from RFC 3490 on each label
        1. Steps 6 and 7 shouldn't be necessary because the RFC 3492 [decoding procedure](https://datatracker.ietf.org/doc/html/rfc3492#section-6.2) is guaranteed to be one-to-one provided the implementations errors in the conditions described
    4. Output everything

What's still unclear to me is:
- can the domain be percent-encoded as well as use IDNA?
- can the length of an IDNA label be known ahead of time (for `lengthIfKnown`)?

I might take a stab at implementing this at some point. If I've missed something, let me know.

**Comment by karwa** [comment]
Hi!

As it happens, I'm actually working on this right now 😄 You can check it out on the [`idna_proto` branch](https://github.com/karwa/swift-url/tree/idna-proto). I have another commit coming later today or tomorrow with some further optimisations for the Unicode data tables, and there's some other gaps that are not implemented yet.

But so far, it has the IDNA mapping data and the basic skeleton of the processing pipeline. I still need to add data for the `Bidi_Class` and `Joining_Type` properties, so that we can accurately validate bidirectional domains such as Arabic and Hebrew, and then it's just general cleanup, testing and benchmarking.

I'm testing it using the UTS46 conformance suite. Of the 6235 tests, 5272 rely on the missing data and cannot be tested, and 963 tests do not rely on that data and we pass them all.

```swift
let url = WebURL("https://faß.api.你好你好.com/foo/bar")!
print(url)  // "https://xn--fa-hia.api.xn--6qqa088eba.com/foo/bar"

let url = WebURL("https://hello.💩.com/foo/bar")!
print(url)  // "https://hello.xn--ls8h.com/foo/bar"

let url = WebURL("https://０Ｘｃ０．０２５０．０１/foo/bar")!
print(url)  // "https://192.168.0.1/foo/bar"

// (yes, that's an exotic IPv4 address written using full-width characters!)
```

Besides just parsing IDNA domains, we'll also need to think about APIs for domain rendering.

[TR36 has an overview](https://www.unicode.org/reports/tr36/#international_domain_names) of some of the issues that can emerge with inconsiderate rendering of IDNA domains, so I think we actually want a step with that kind of terminology: "rendering". It can take display information in to consideration (such as fonts and user locale) to produce an appropriate presentation form of the domain.

That means there isn't currently a simple "decode IDNA" function. Instead, `ToUnicode` iterates each label as a buffer of Unicode scalars.

```swift
 var result = ""
 let success = IDNA.toUnicode(utf8: source) { label, trailingDot in
   result.unicodeScalars += label
   if trailingDot { result += "." }
   return true
}
return success ? result : nil
```

Obviously, that's pretty user-hostile, so currently my idea is that eventually there will be some kind of renderer protocol which encapsulates that logic (like there are percent-encode sets), and you'd pick a strategy for the situation (maybe `.alwaysUnicode`, or `.bestForCurrentLocale`, etc). 

If it helps, I'm picturing some kind of API, let's call it `RenderDomain`, and there is some function `DecidePresentationStrategyForLabel` which examines the domain label and decides the best way to show it to the user:

```swift
 func RenderDomain(_ input: String) -> String? {
   var result = ""
   let success = IDNA.toUnicode(utf8: input.utf8) { label, needsTrailingDot in
     switch DecidePresentationStrategyForLabel(label) {
     // Unicode presentation.
     case .unicode:
       result.unicodeScalars.append(contentsOf: label)

     // The checker think the Unicode presentation is potentially misleading,
     // and we should write it as Punycode instead.
     case .punycode:
       Punycode.encode(label) { ascii in
         result.unicodeScalars.append(Unicode.Scalar(ascii))
       }

     // Other strategies, beyond Punycode...?
     case .highlightConfusableWithKnownBrand:
       /* ... Maybe use AttributedString to flag it for UI code? */
       /* ... Maybe an extra warning for certain actions, like making a purchase/entering a password? */
     }

     // Remember the dot :)
     if needsTrailingDot { result += "." }
     return true
   }
   return success ? result : nil
 }

 RenderDomain("x.example.com")
 // ✅ "x.example.com" (ASCII)

 RenderDomain("shop.xn--igbi0gl.com")
 // ✅ "shop.أهلا.com"

 RenderDomain("xn--pple-poa.com")
 // ✅ "xn--pple-poa.com", NOT "åpple.com"

 RenderDomain("岍岊岊岅岉岎.com")
 // ✅ "岍岊岊岅岉岎.com" NOT "xn--citibank.com"
```

I think designing a good API (and writing some first attempts at built-in renderers) will be the hardest part of this.

**Comment by shadowfacts** [comment]
Hah, what a coincidence!

I think your implementation so far looks great. `WebURL.Host` should definitely know if it contains an IDNA label. The API you sketched out for letting the end consumer looks interesting. I think helpers for rendering the domain as unicode and punycode should definitely be builtin. For renderers more complex than that, I think the best API is like what `IDNA.toUnicode` has—a closure that lets the consumer do whatever it wants.

Speaking selfishly, I don't need to display IDNA domains, just parse them, so the current state of the prototype would fulfill my use case. For an initial implementation, I think only having the unicode and punycode strategies for IDNA labels is fine. Having helpers for detecting confusable labels definitely makes sense, it seems like an area where it's easy to overlook things, but I don't think it should block the initial implementation.
